users:
  asdb:
    username: asdb
    articleIds:
      - 1
    commentIds: []
  mdol:
    username: mdol
    articleIds:
      - 2
    commentIds:
      - 1
  robson:
    username: robson
    articleIds:
      - 3
    commentIds: []
  John Doe:
    username: John Doe
    articleIds: []
    commentIds: []
  Robson:
    username: Robson
    articleIds: []
    commentIds:
      - 2
articles:
  '1':
    id: 1
    title: bad
    url: 'http://www.google.com'
    username: asdb
    commentIds: []
    upvotedBy:
      - robson
      - John Doe
    downvotedBy: []
    comments: []
  '2':
    id: 2
    title: Title
    url: 'http://google.com'
    username: mdol
    commentIds:
      - 1
    upvotedBy:
      - robson
      - John Doe
    downvotedBy:
      - mdol
    comments:
      - &ref_0
        id: 1
        body: Hi
        username: mdol
        articleId: 2
        upvotedBy: []
        downvotedBy: []
  '3':
    id: 3
    title: Live do alanzoka
    url: 'https://www.twitch.tv/alanzoka'
    username: robson
    commentIds:
      - 2
    upvotedBy:
      - robson
      - John Doe
    downvotedBy: []
    comments:
      - &ref_1
        id: 2
        articleId: 3
        username: Robson
        body: Teste
        upvotedBy: []
        downvotedBy: []
comments:
  '1': *ref_0
  '2': *ref_1
nextCommentId: 3
nextUserId: 1
nextArticleId: 4
